### ISSUE TITLE
Use of CDATA Should be Avoided

### ISSUE THREAD

**Issue by mikegreiling** [NetzwergX/jekyll-template-toolkit#2]
Liquid provides a `xml_escape` filter that will work nicely in its place. CDATA has some potential pitfalls when it comes to content-type encoding and GitHub Pages serves up XML with `us-ascii` encoding rather than `utf-8` [for some crazy reason](http://taylor.fausak.me/2012/04/26/serving-atom-feeds-with-github-pages/).

See [here](http://en.wikipedia.org/wiki/CDATA#Issues_with_encoding) for further explanation.

I'd use:

```
<block>{{ post.attr | xml_escape }}</block>
```

or:

```
<block>{{ post.attr | strip_html }}</block>
```

in place of:

```
<block><![CDATA[{{ post.attr }}]]></block>
```

**Comment by NetzwergX** [comment]
The next iteration of the templates will probably deprecate the feed.xml file for this exakt reason. There will be seperate feed.atom and feed.rss files, which GitHub fortunately delivers with the right headers (application/atom.xml defaults to UTF-8, and the **recommended** charset will be UTF-8).
